[package]
name = "lib-git"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
git2 = { workspace = true }
serde = {workspace = true}
serde_json = {workspace = true}
derive_more = {workspace = true}
gix = {workspace=true}
serde_with = {workspace=true }
