[package]
name = "lib-rpc"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
rpc-router = {workspace = true}
derive_more = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
lib-core = {path="../lib-core"}
